name: nwb-explore
channels:
  - conda-forge
  - default
dependencies:
  - python=3.11
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - pynwb
  - h5py
  - jupyterlab
  - ipython_genutils
  - pip
  - pip:
    - nwbwidgets

